### ISSUE TITLE
The numbers is emoji

### ISSUE THREAD

**Issue by GG526** [piterwilson/StringEmoji#1]
```
let string = "123455"
printf(string.first?.isEmoji)
```
log: true

**Comment by piterwilson** [comment]
The number keypads are an interesting case. Consider the 0️⃣ keypad for example. According to the emojilist website:

> The Keycap Digit Zero emoji is a sequence of the 0 Digit Zero and ⃣ Combining Enclosing Keycap emojis

Defined as `U+0030 U+FE0F U+20E3` with `U+0030` being a the '0'

In other words, I can see that the numbers themselves are part of the emoji character, which in my function gets evaluated to true.

Thanks for the report, i will add an update

**Comment by GG526** [comment]
```
public let numbers: String = "0123456789"
extension Character {
    var isEmoji: Bool {
        for char in numbers {
            if char == self {
                return false
            }
        }
        return emojiCharacterSet.contains(String(self).unicodeScalars.first!)
    }
}
```
I think it should be modified like this.
